### ISSUE TITLE
Sending Structured Logging to insightOps?

### ISSUE THREAD

**Issue by PureKrome** [rapid7/r7insight_dotnet#15]
Hi there. 

I'm trying to see if this class library can send Structured Logging data to insight ops? Right now, it just sends the data as a single line of text and the insightOps's "figures out" the structure and then converts the pieces of data to relevant fields.

Is there any other tricks to make this more programable?

Here's an example:

```
// Log some fake info.
var position = new { Latitude = 25, Longitude = 134 };
var elapsedMs = 34;
log.Information("Processed {@Position} in {Elapsed:000} ms.", position, elapsedMs);
```

This is what insightOps ends up storing/showing:

![image](https://user-images.githubusercontent.com/899878/147092482-7c2e93fa-b47c-40fe-a6bc-dac4437abd66.png)
![image](https://user-images.githubusercontent.com/899878/147092516-88e82988-12cf-4d62-b0f8-30c9b441899e.png)

while using another app, it shows this more accurately:

![image](https://user-images.githubusercontent.com/899878/147092591-e1e1c07c-7963-4c0c-bf96-0d67e03f9c0e.png)

and of course, in the other app .. we can accurately search on `Latitude` 

![image](https://user-images.githubusercontent.com/899878/147092755-d38bdc26-f079-4a51-8719-250e4d236095.png)

The reason for the difference _currently_ is that I'm ending up having to convert the log to a string (which flattens the log and basically removes any structure from it). I then send this flattened string up to insightOps. So any chance of 'structure' is now lost.

So can InsightOps accept structured logging and then if it can, how do we send that up?

**Comment by PureKrome** [comment]
I think I found the answer.

The trick is to send the data as JSON to insightOps.

Here's the project I made, which does this: https://github.com/PureKrome/serilog-sinks-insightops

The readme explain the options of using plain logging or structured logging to insightOps. 

👋🏻

**Comment by caleb3141** [comment]
I had good luck using this log4net json library: https://gitlab.com/gdziadkiewicz/log4net.Ext.Json

When sending as JSON, the data is imported into Rapid7 as different columns in the table view.
