### ISSUE TITLE
Target cannot be found: 'Insight' NLog Issue

### ISSUE THREAD

**Issue by goodwince** [rapid7/r7insight_dotnet#22]
Hi,

I have R7Insight.Core and R7Insight.NLog installed through NuGet. The local log target is working - however, NLog upon starting states it cannot find the Insight target.

`
Warn Error has been raised. Exception: NLog.NLogConfigurationException: Failed to create target type: Insight
 ---> System.ArgumentException: Target cannot be found: 'Insight'
   at NLog.Config.Factory2.CreateInstance(String itemName)
   at NLog.Config.LoggingConfigurationParser.CreateTargetType(String targetTypeName)
   `

I looked through the repo here and it should be there. Any advice is welcome. Here's my NLog.Config for target

`<target name="insightops" type="Insight" region="us2" debug="true" usessl="false" token="MY-TOKEN">`

**Comment by snakefoot** [comment]
The [NLog docs](https://docs.rapid7.com/insightops/nlog/) shows this example:
```xml
<nlog throwConfigExceptions="true">
  <extensions>
    <add assembly="R7Insight.NLog" />
  </extensions>
  <targets>
    <target name="insightops" type="Insight" region="us" debug="true" usessl="false" />
  </targets>
  <rules>
    <logger name="*" minLevel="Debug" appendTo="insightops"/>
  </rules>
</nlog>
```
Did you remember to include `R7Insight.NLog` as NLog extension?

**Comment by goodwince** [comment]
That fixed it. Thank you!
